linters:
  disable-all: true
  enable:
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
